### ISSUE TITLE
schwab-client-example hangs

### ISSUE THREAD

**Issue by higgsja** [gporter0205/schwab-api-client#14]
Two errors on compiling:
1. ClientTokenHandler: could not find org.hetbrains.annotations.NotNull. I changed to using jakarta.validation.constraings.
2. SchwabApiClientHandler:  Error creating bean with name 'schwabApiClientHandler': Injection of autowired dependencies failed. Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'schwab-api.userId' in value "${schwab-api.userId}". I added schwab-api.userId=MyId where MyId is my normal Schwab login ID.

This gets it to run but it hangs as shown here
`2024-08-21T17:35:56.434-05:00  INFO 725309 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)`
`2024-08-21T17:35:56.454-05:00  INFO 725309 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]`
`2024-08-21T17:35:56.454-05:00  INFO 725309 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.26]`
`2024-08-21T17:35:56.548-05:00  INFO 725309 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext`
`2024-08-21T17:35:56.550-05:00  INFO 725309 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1255 ms`
`2024-08-21T17:35:57.277-05:00  INFO 725309 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'`
`2024-08-21T17:35:57.293-05:00  INFO 725309 --- [           main] c.p.s.e.SchwabApiClientApplication       : Started SchwabApiClientApplication in 2.593 seconds (process running for 2.974)`
 
I've set a break point at SchwabApiClientHandler.init but it never gets there.

In application.yml, I set the following:
`clientId: <my App Key>`
`clientSecret: <my Secret>`
`redirect-uri: https://127.0.0.1`
I've tried both with and without quotes

In the debugging window, the last item is "Notification Thread running"

I'm sure this is something simple but I'm out of ideas.

Can you help?

**Comment by gporter0205** [comment]
Two things jump out at me.  I eliminated the org.jetbrains.annotations.NotNull dependency so make sure you are using the latest version 0.1.5.  The other thing is make sure that you have the application.yml entries under schwab-api and oauth2 like this:

```
schwab-api:
  oauth2:
    clientId: <my App Key>
    clientSecret: <my Secret>
    redirect-uri: https://127.0.0.1
```

**Comment by gporter0205** [comment]
Also check out the wiki.  It has some step-by-step instructions to get you started.  Hopefully, that will help.  https://github.com/gporter0205/schwab-api-client/wiki

**Comment by gporter0205** [comment]
You might want to pull some changes I just made to schwab-client-example project.  I corrected the problem with @NotNull that you mentioned, moved the Schwab account userId definition out of the yml (have to hard code it in the example) and also fixed the init() method never getting called.

**Comment by higgsja** [comment]
Ok, did all that, still the same issues: hangs and never hits init().

Other thoughts on where I might look for issues?

Thanks!!

**Comment by gporter0205** [comment]
The example application isn't a full featured application,  It just has a couple of rest services set up that each call an endpoint of the Schwab API to give you an example to follow to setup your own application.  It's not "hanging".  It just fires up a web server and waits for something to call one of it's web services.

**Comment by higgsja** [comment]
You commented
> The example application isn't a full featured application, It just has a couple of rest services set up that each call an endpoint of the Schwab API to give you an example to follow to setup your own application. It's not "hanging". It just fires up a web server and waits for something to call one of it's web services.

Ok, apparently I'm not savvy enough to add the final piece that will return data.

My goal at the moment is simple: pull stock and option market data daily for high, low, close.

Can you point me toward some examples to make that happen?

Really appreciate any help!
